// Autogenerated by app.quicktype.io
// To parse this data:
//
//   import { Convert, OverpassResultSet } from "./overpassResultSet";
//
//   const overpassResultSet = Convert.toOverpassResultSet(json);
//
// These functions will throw an error if the JSON doesn't
// match the expected interface, even if the JSON is valid.

export interface OverpassResultSet {
    version?:   number;
    generator?: string;
    osm3S?:     Osm3S;
    elements?:  Element[];
}

export interface Element {
    type?:  string;
    id?:    number;
    lat?:   number;
    lon?:   number;
    tags?:  Tags;
    nodes?: number[];
}

export interface Tags {
    addrPostcode?:    string;
    amenity?:         string;
    cuisine?:         string;
    name?:            string;
    addrCity?:        string;
    addrHousenumber?: string;
    addrState?:       string;
    addrStreet?:      string;
    phone?:           string;
    website?:         string;
    building?:        string;
    buildingLevels?:  string;
    ele?:             string;
    height?:          string;
    openingHours?:    string;
}

export interface Osm3S {
    timestampOsmBase?: Date;
    copyright?:        string;
}

// Converts JSON strings to/from your types
// and asserts the results of JSON.parse at runtime
export class Convert {
    public static toOverpassResultSet(json: string): OverpassResultSet {
        return cast(JSON.parse(json), r("OverpassResultSet"));
    }

    public static overpassResultSetToJson(value: OverpassResultSet): string {
        return JSON.stringify(uncast(value, r("OverpassResultSet")), null, 2);
    }
}

function invalidValue(typ: any, val: any, key: any = ''): never {
    if (key) {
        throw Error(`Invalid value for key "${key}". Expected type ${JSON.stringify(typ)} but got ${JSON.stringify(val)}`);
    }
    throw Error(`Invalid value ${JSON.stringify(val)} for type ${JSON.stringify(typ)}`, );
}

function jsonToJSProps(typ: any): any {
    if (typ.jsonToJS === undefined) {
        const map: any = {};
        typ.props.forEach((p: any) => map[p.json] = { key: p.js, typ: p.typ });
        typ.jsonToJS = map;
    }
    return typ.jsonToJS;
}

function jsToJSONProps(typ: any): any {
    if (typ.jsToJSON === undefined) {
        const map: any = {};
        typ.props.forEach((p: any) => map[p.js] = { key: p.json, typ: p.typ });
        typ.jsToJSON = map;
    }
    return typ.jsToJSON;
}

function transform(val: any, typ: any, getProps: any, key: any = ''): any {
    function transformPrimitive(typ: string, val: any): any {
        if (typeof typ === typeof val) return val;
        return invalidValue(typ, val, key);
    }

    function transformUnion(typs: any[], val: any): any {
        // val must validate against one typ in typs
        const l = typs.length;
        for (let i = 0; i < l; i++) {
            const typ = typs[i];
            try {
                return transform(val, typ, getProps);
            } catch (_) {}
        }
        return invalidValue(typs, val);
    }

    function transformEnum(cases: string[], val: any): any {
        if (cases.indexOf(val) !== -1) return val;
        return invalidValue(cases, val);
    }

    function transformArray(typ: any, val: any): any {
        // val must be an array with no invalid elements
        if (!Array.isArray(val)) return invalidValue("array", val);
        return val.map(el => transform(el, typ, getProps));
    }

    function transformDate(val: any): any {
        if (val === null) {
            return null;
        }
        const d = new Date(val);
        if (isNaN(d.valueOf())) {
            return invalidValue("Date", val);
        }
        return d;
    }

    function transformObject(props: { [k: string]: any }, additional: any, val: any): any {
        if (val === null || typeof val !== "object" || Array.isArray(val)) {
            return invalidValue("object", val);
        }
        const result: any = {};
        Object.getOwnPropertyNames(props).forEach(key => {
            const prop = props[key];
            const v = Object.prototype.hasOwnProperty.call(val, key) ? val[key] : undefined;
            result[prop.key] = transform(v, prop.typ, getProps, prop.key);
        });
        Object.getOwnPropertyNames(val).forEach(key => {
            if (!Object.prototype.hasOwnProperty.call(props, key)) {
                result[key] = transform(val[key], additional, getProps, key);
            }
        });
        return result;
    }

    if (typ === "any") return val;
    if (typ === null) {
        if (val === null) return val;
        return invalidValue(typ, val);
    }
    if (typ === false) return invalidValue(typ, val);
    while (typeof typ === "object" && typ.ref !== undefined) {
        typ = typeMap[typ.ref];
    }
    if (Array.isArray(typ)) return transformEnum(typ, val);
    if (typeof typ === "object") {
        return typ.hasOwnProperty("unionMembers") ? transformUnion(typ.unionMembers, val)
            : typ.hasOwnProperty("arrayItems")    ? transformArray(typ.arrayItems, val)
            : typ.hasOwnProperty("props")         ? transformObject(getProps(typ), typ.additional, val)
            : invalidValue(typ, val);
    }
    // Numbers can be parsed by Date but shouldn't be.
    if (typ === Date && typeof val !== "number") return transformDate(val);
    return transformPrimitive(typ, val);
}

function cast<T>(val: any, typ: any): T {
    return transform(val, typ, jsonToJSProps);
}

function uncast<T>(val: T, typ: any): any {
    return transform(val, typ, jsToJSONProps);
}

function a(typ: any) {
    return { arrayItems: typ };
}

function u(...typs: any[]) {
    return { unionMembers: typs };
}

function o(props: any[], additional: any) {
    return { props, additional };
}

function m(additional: any) {
    return { props: [], additional };
}

function r(name: string) {
    return { ref: name };
}

const typeMap: any = {
    "OverpassResultSet": o([
        { json: "version", js: "version", typ: u(undefined, 3.14) },
        { json: "generator", js: "generator", typ: u(undefined, "") },
        { json: "osm3s", js: "osm3S", typ: u(undefined, r("Osm3S")) },
        { json: "elements", js: "elements", typ: u(undefined, a(r("Element"))) },
    ], false),
    "Element": o([
        { json: "type", js: "type", typ: u(undefined, "") },
        { json: "id", js: "id", typ: u(undefined, 0) },
        { json: "lat", js: "lat", typ: u(undefined, 3.14) },
        { json: "lon", js: "lon", typ: u(undefined, 3.14) },
        { json: "tags", js: "tags", typ: u(undefined, r("Tags")) },
        { json: "nodes", js: "nodes", typ: u(undefined, a(0)) },
    ], false),
    "Tags": o([
        { json: "addr:postcode", js: "addrPostcode", typ: u(undefined, "") },
        { json: "amenity", js: "amenity", typ: u(undefined, "") },
        { json: "cuisine", js: "cuisine", typ: u(undefined, "") },
        { json: "name", js: "name", typ: u(undefined, "") },
        { json: "addr:city", js: "addrCity", typ: u(undefined, "") },
        { json: "addr:housenumber", js: "addrHousenumber", typ: u(undefined, "") },
        { json: "addr:state", js: "addrState", typ: u(undefined, "") },
        { json: "addr:street", js: "addrStreet", typ: u(undefined, "") },
        { json: "phone", js: "phone", typ: u(undefined, "") },
        { json: "website", js: "website", typ: u(undefined, "") },
        { json: "building", js: "building", typ: u(undefined, "") },
        { json: "building:levels", js: "buildingLevels", typ: u(undefined, "") },
        { json: "ele", js: "ele", typ: u(undefined, "") },
        { json: "height", js: "height", typ: u(undefined, "") },
        { json: "opening_hours", js: "openingHours", typ: u(undefined, "") },
    ], false),
    "Osm3S": o([
        { json: "timestamp_osm_base", js: "timestampOsmBase", typ: u(undefined, Date) },
        { json: "copyright", js: "copyright", typ: u(undefined, "") },
    ], false),
};
